### PR TITLE
Add official Remix example to Remix guide

### LINKED ISSUE #1353: Add official Remix example to examples
### Subject

Remix Guide

### Description

Add https://github.com/remix-run/examples/tree/main/chakra-ui.

### PR DESCRIPTION
**Pull request by debater-coder**
Closes #1353.

# 📝 Description
The goal of this pull request is to add the official Remix example for Chakra UI to the 'Community Boilerplate' section of the 'Remix guide'.

# 💣 Is this a breaking change (Yes/No):
No.

# 📝 Additional information
Screenshot:
image

### CODE REVIEW

**Comment by aacevski** [comment]
Hey @debater-coder, thank you for your contribution! 💖 I just want say, is it possible if we change this to use Sandpack so it could be interactable instead of the URL?

image

Like the theming showcase of most component is a pretty good example:
https://chakra-ui.com/docs/components/button/theming#showcase

**Comment by debater-coder** [comment]
The main issue here is that [Sandpack does not support Remix](https://sandpack.codesandbox.io/docs/faq#does-sandpack-support-nextjs-or-other-server-side-applications). Remix does provide a [CodeSandbox](https://codesandbox.io/s/github/remix-run/examples/tree/main/chakra-ui) which we can embed, but it won't be possible to theme it like we do for Sandpack.

**Comment by aacevski** [comment]
> Updated screenshot @aacevski: image

Hey, sorry, I wasn't aware that Remix isn't supported by Sandpack. Sorry for asking for one more change but is it okay if we remove the `Community Boilerplates` part and add a heading which says:
# Template

If you're starting a new project and would like to cut down on configuration time, you can use the official template on how to use Chakra UI with Remix:

**Comment by debater-coder** [comment]
**Updated Screenshot** @aacevski:
image

**Comment by debater-coder** [comment]
I'm going to be on holidays, so I won't be able to work on this for the next few weeks.

**Comment by debater-coder** [comment]
bump @aacevski

**Review by aacevski — APPROVED** [review]
This looks good, thank you!

**Pull request merged**
