### PR TITLE
docs(recipes): Adding floating labels recipe

### LINKED ISSUE #212: Floating Labels
### Description

Floating Labels in Chakra-UI. This topic has come up a couple of times, and given that it has a11y advantages and it is a very popular style, I think it should be part of Chakra-UI. Either as a Guide or as part of the Library. 

See more: chakra-ui/chakra-ui#1744 chakra-ui/chakra-ui#5120

### Problem Statement/Justification

This topic came up a couple of times, but I haven't found a solution posted yet.

### Proposed Solution or API

https://user-images.githubusercontent.com/6193042/148698023-c0226d27-b164-437c-9a13-7459e2bf6597.mov

Add floating as a variant to `FormControl` 
`form.ts`
Sample:

```
export default {
  parts: parts.keys,
  baseStyle,
  variants: {
    floating: {
      container: {
        _focusWithin: {
          label: {
            transform: "scale(0.825) translateY(-24px) translateX(-10px)",
          },
        },
        "input:not(:placeholder-shown) + label": {
          transform: "scale(0.825) translateY(-24px) translateX(-10px)",
        },
        label: {
          top: 0,
          left: 0,
          zIndex: 2,
          position: "absolute",
          backgroundColor: "white",
          mx: 3,
          px: 1,
          my: 2,
        },
      },
    },
  },
}
```
Usage: 
```
 <FormControl variant="floating" id="first-name" isRequired isInvalid>
    <Input placeholder=" " /> // <- Input needs to be before FormLabel for CSS Selector
    <FormLabel>First name</FormLabel>
    <FormHelperText>Keep it very short and sweet!</FormHelperText>
    <FormErrorMessage>Your First name is invalid</FormErrorMessage>
  </FormControl>
```

### Alternatives

As @segunadebayo recommended in a previous ticket, this could go in as a Guide / Recipe.

### Additional Information

I have built this with various approaches in client projects at this point and I figured I can put a more formal solution together to bring back into the library. Just let me know which route you want to go and I can toss something together.

Admittedly, i am a bit worried how stable it will be as part of the library, since some of the properties will be dependent on input styles. Which makes this a safer addition as a guide.

### PR DESCRIPTION
**Pull request by Patrick-Ullrich**
Closes #212 

## 📝 Description

Adding a recipe for adding floating labels to Chakra UI. This should give users all the tools needed to implement this or any other style.

## ⛳️ Current behavior (updates)

N/A

## 🚀 New behavior

N/A

## 💣 Is this a breaking change (Yes/No):

No

## 📝 Additional Information

See the full code example here: https://codesandbox.io/s/optimistic-shockley-g0uls?file=/src/index.tsx

### CODE REVIEW

**Review by nikolovlazar — CHANGES_REQUESTED** [review]
Thank you for the effort @Patrick-Ullrich! Having the floating labels in recipes is a good idea. I do have some points for you to do until this PR is ready to be merged:

- Make sure you add the link of this recipe in the Recipes section in the sidebar (hint: `configs/guides-sidebar.json`)
- Make sure you add the link of this recipe in the Search as well (hint: `configs/search-meta.json`)
- It would be better if you wrap the code snippet with the `SandpackEmbed` instead of an ordinary code block (hint: `pages/index.tsx` line 290). That way the floating label example will be interactive as well.
- Remove the `This recipe was inspired by #212` blockquote from the content

If you need additional help with some of these points let me know. I'd be happy to guide you through.

**Comment by Patrick-Ullrich** [comment]
Ignore that mess... I typoed in a `git --amend` and created a big ol mess. Should be all cleaned up now. 

I think i implemented all your recommendations @nikolovlazar , except for the `SandpackEmbed`. It did not like the import. Do we have an example of SandpackEmbed working in a `mdx` file yet? Or can I replace the .mdx with a .tsx file?

Let me know and I can make that change as well.

**Comment by nikolovlazar** [comment]
@Patrick-Ullrich here's what you need to do:

- [ ] Register the `SandpackEmbed` component in `src/components/mdx-components/mdx-components.tsx` at the bottom of the file:
```javascript
  EggheadCourseBanner,
  SandpackEmbed: (props) => (
    <Box my={6}>
      <SandpackEmbed {...props} />
    </Box>
  ),
}
```
- [ ] Refactor your MDX file to use the `SandpackEmbed` component instead of the codeblock:
```javascript
<SandpackEmbed
  options={{
    editorHeight: 600,
    editorWidthPercentage: 60,
  }}
  files={{
    '/src/App.tsx': `import {
  Container,
  ChakraProvider,
  FormControl,
  FormErrorMessage,
  FormHelperText,
  FormLabel,
  Input,
  extendTheme,
  Box,
} from '@chakra-ui/react'
const activeLabelStyles = {
  transform: 'scale(0.85) translateY(-24px) translateX(-10px)',
}
export const theme = extendTheme({
  components: {
    Form: {
      variants: {
        floating: {
          container: {
            _focusWithin: {
              label: {
                ...activeLabelStyles,
              },
            },
            'input:not(:placeholder-shown) + label, .chakra-select__wrapper + label':
              {
                ...activeLabelStyles,
              },
            label: {
              top: 0,
              left: 0,
              zIndex: 2,
              position: 'absolute',
              backgroundColor: 'white',
              pointerEvents: 'none',
              mx: 3,
              px: 1,
              my: 2,
            },
          },
        },
      },
    },
  },
})
export default function App() {
  return (
    <ChakraProvider theme={theme}>
      <Box p={8}>
        <FormControl variant='floating' id='first-name' isRequired isInvalid>
          <Input placeholder=' ' />
          {/* It is important that the Label comes after the Control due to css selectors */}
          <FormLabel>First name</FormLabel>
          <FormHelperText>Keep it very short and sweet!</FormHelperText>
          <FormErrorMessage>Your First name is invalid</FormErrorMessage>
        </FormControl>
      </Box>
    </ChakraProvider>
  )
}
`,
    '/src/index.tsx': `import * as React from "react";
import { render } from "react-dom";
import { ChakraProvider } from "@chakra-ui/react";

import App from './App'

const rootElement = document.getElementById("root");

render(
   <ChakraProvider>
     <App />
   </ChakraProvider>,
   rootElement,
);`,
   }}
   zIndex={0}
   tabIndex={-1}
/>
```
- [ ] Remove the bottom CodeSandbox link, and also the last sentence before the codeblock.

**Comment by Patrick-Ullrich** [comment]
Done and done 👍

**Review by nikolovlazar — CHANGES_REQUESTED** [review]
We should also remove the `Find a complete working solution in the Code Sandbox.` sentence at the end, since there's no other solution than this.

**Comment by nikolovlazar** [comment]
@allcontributors please add @Patrick-Ullrich for docs.

**Comment by Djamilson** [comment]
components: {
        Form: {
            variants: {
                floating: {
                    container: {
                        _focusWithin: {
                            label: {
                                ...activeLabelStyles
                            }
                        },
                        'input:not(:placeholder-shown) + label, .chakra-select__wrapper + label, textarea:not(:placeholder-shown) ~ label':
                            {
                                ...activeLabelStyles
                            },

                        label: {
                            top: 0,
                            left: 0,
                            zIndex: 2,
                            position: 'absolute',
                            color: 'cinza.650',
                            backgroundColor: 'white.900',
                            pointerEvents: 'none',
                            mx: 3,
                            px: 1,
                            my: 3,
                            transformOrigin: 'left top',                     
                            ...activeLabelStyles
                        }
                    }
                }
            }
        }
    }

**Pull request merged**
