### PR TITLE
[Contributing] typo

### PR DESCRIPTION
**Pull request by Luccasoli**
## 📝 Description

Would probably have a `yarn test`, but there are no tests 

## ⛳️ Current behavior (updates)

Correcting a typo

## 🚀 New behavior

Deleted unnecessary text

## 💣 Is this a breaking change (Yes/No):

No

### CODE REVIEW

**Comment by nikolovlazar** [comment]
Good catch, @Luccasoli! Thank you for opening this PR 💚 As I scroll through the `CONTRIBUTING.md` file I also noticed there's a reference to testing in the "Commit Convention" section, so you can remove that too.

These are leftovers from the main `chakra-ui` repo after we split the components with the docsite.

**Comment by Luccasoli** [comment]
@nikolovlazar thanks! And yes, i'll open a new PR solving what you mentioned as soon as possible!

**Comment by nikolovlazar** [comment]
No need to, @Luccasoli. Just push a new commit to this one.

**Comment by Luccasoli** [comment]
@nikolovlazar done! 😁

**Pull request merged**
