### PR TITLE
Add Embedery

### PR DESCRIPTION
**Pull request by Pinguii**
## 📝 Description
Add Embedery.com to the showcase. We are proud users of ChakraUI.

## 💣 Is this a breaking change (Yes/No):
No

### CODE REVIEW

**Comment by aacevski** [comment]
Hey @Pinguii! Thank you for your submission, I just went through the site and I see that this was mainly done in Tailwind, I was interested in what part of this website is using Chakra UI? 🙌🏼

**Comment by Pinguii** [comment]
Hi @aacevski thank you for reviewing our website.

We do use Chakra UI quite a bit in our main application compared to our landing website, although on the landing website we have some forms and Chakra UI components implemented and we are currently transitioning some of our landing pages to Chakra UI components.

Let us know if you want to see anything more specific.

Thank you again.

**Comment by nikolovlazar** [comment]
@Pinguii we currently don't accept community submissions to the showcase page. Thank you for taking the time to open a PR though 🙌 we hope you enjoy working with Chakra UI!

**Comment by Pinguii** [comment]
Hi, @nikolovlazar that's fine, thank you both for taking the time to consider the change.

**Pull request closed without merging**
