### PR TITLE
Improve `/changelog` page performance

### LINKED ISSUE #200: Improve `/changelog` page performance
### Subject

Changelog

### Description

There's a warning from Next.js about the changelog page being too large in size.

> Warning: data for page "/changelog" is 250 kB, this amount of data can reduce performance.

I'm thinking we can use progressive disclosure to improve the page's performance. Here are some ideas:

- Show the changelog for only the current version, and hide the rest
- Include the Table of Content on the right side that shows the previous versions so the users can navigate to the version they're interested in.
- Consider using a dynamic route `/changelog/<version>` to determine which changelog to show

### PR DESCRIPTION
**Pull request by jacobhq**
Closes #200

## Proposed structure

- [x] Split markdown files by date ~~**or** implement code to split by heading~~
- [ ] Create API route to fetch these files
- [ ] Use SWR pagination to optimise performance of the changelog page
- [ ] Update changelog generation (help wanted)

*I decided to split the markdown files, and name them by date and version.*

### CODE REVIEW

**Review by noobinthisgame — COMMENTED** [review]
Hey @jacobhq,
did you check how the content.mdx file for the changelog gets generated before you split this up? The file is generated automatically by a script with the actually changelog from the main repo. You would have to update that script aswell to keep the logs split like this. Otherwise the next time the script runs it will add a content.mdx on top of your changes

**Comment by jacobhq** [comment]
> Hey @jacobhq, did you check how the content.mdx file for the changelog gets generated before you split this up? The file is generated automatically by a script with the actually changelog from the main repo. You would have to update that script aswell to keep the logs split like this. Otherwise the next time the script runs it will add a content.mdx on top of your changes

Thanks for pointing that out, I'll make sure to update the script. What do you think about the whole idea of splitting the `content.mdx` file?

**Comment by noobinthisgame** [comment]
No problem :) 
I think it's a good idea which plays well into the comments and ideas that @segunadebayo left in the issue. Like this you can easier control what to show / hide and reduce loading.

**Comment by noobinthisgame** [comment]
Hey @jacobhq, what's the status on this? Do you need help with anything ? If so let us know :)

**Comment by noobinthisgame** [comment]
What you can do is read the content fetched and split it up by date. Every date can then be pushed into a single file for example. You can leverage the code that is already there for writing files.

**Comment by jacobhq** [comment]
Cool, I'll close this, and start a new PR.

**Pull request closed without merging**
