### PR TITLE
docs: add docs for range slider hook

### PR DESCRIPTION
**Pull request by Tisks**
Closes [#1288](https://github.com/chakra-ui/chakra-ui-docs/issues/1288)

## 📝 Description

This PR adds one docs pages for the useRangeSlider hook. It also provides an example.

## ⛳️ Current behavior (updates)

There's currently no documentation for the useRangeSlider hook

## 🚀 New behavior

This PR adds in the documentation how to use the useRangeSlider hook

## 💣 Is this a breaking change (Yes/No):

No

### CODE REVIEW

**Comment by Tisks** [comment]
@estheragbaje @segunadebayo please review 🙏 , I simplified it like the one in [#1281](https://github.com/chakra-ui/chakra-ui-docs/pull/1281), same style

**Comment by Tisks** [comment]
@estheragbaje @segunadebayo Srry about being pedantic but I remind you about this PR 🙌

**Review by aacevski — CHANGES_REQUESTED** [review]
Hey @Tisks! Thank you for your contribution 💖 I have some comments regarding this pull request:
- image
The colors here don't really go well together, can you please change the color scheme?

- I feel like we can simplify the code, I know you had a previously opened PR regarding this and simplified it but to me there's a lot of code still. On top of simplifying the code, why don't you try to seperate things into components? 

If you need help, I can help you on simplifying the code a little so the user doesn't feel overwhelmed.

**Comment by Tisks** [comment]
>   The colors here don't really go well together, can you please change the color scheme?
> * I feel like we can simplify the code, I know you had a previously opened PR regarding this and simplified it but to me there's a lot of code still. On top of simplifying the code, why don't you try to seperate things into components?
> 
> If you need help, I can help you on simplifying the code a little so the user doesn't feel overwhelmed.

Yeah... the color scheme doesn't match and I don't know which colors would... can you help me in that?

Also please help me because I reduced as much as I could and regarding separating into components... I didn't see that in the other examples of this type of docs so I didn't do it.

**Comment by aacevski** [comment]
Hey @Tisks, I will leave this comment here as well to give you an idea on how you can seperate the code a little bit and to fix the colors as well:
https://codesandbox.io/s/optimistic-diffie-4e8pkf?file=/src/index.tsx

If you can do this with CodeSandbox so we can't see how it looks. Just like the Showcase examples in the theming documentation of the components, for example Button:
https://chakra-ui-docs-git-fork-tisks-docs-add-docs-fo-1039df-chakra-ui.vercel.app/docs/components/button/theming#showcase

PS: Please update the colors to the ones I'm using in the CodeSanbox as well.

**Review by aacevski — CHANGES_REQUESTED** [review]

**Review by aacevski — APPROVED** [review]

**Pull request merged**
