### PR TITLE
docs(theme): add alpha color pallets

### PR DESCRIPTION
**Pull request by TylerAPfledderer**
## 📝 Description

Adds color pallets for Social Media from the default theme that were missing in the docs.

## 📝 Additional Information

~~Awaiting PR #452 to be merged before updating `search-meta.json`~~ Manually updated `get-search-meta.ts` to go ahead and update the search meta to push for review.

### CODE REVIEW

**Comment by nikolovlazar** [comment]
Hi @TylerAPfledderer! We plan on removing these colors in the future versions. That means we don't need to document them for the time being. Let me confirm with the team and I'll get back to you.

**Comment by nikolovlazar** [comment]
@TylerAPfledderer confirmed. We're going to remove the social colors in the next major release. You can add the Alphas, but I'd also recommend to add a line of text below the "Alphas" title saying "Toggle the site's color mode to see the colors.", because the white alphas on light mode don't have any effect.

**Comment by nikolovlazar** [comment]
@TylerAPfledderer is this ready to be reviewed?

**Comment by TylerAPfledderer** [comment]
> @TylerAPfledderer is this ready to be reviewed?

I can unlock it for review. Can't update the search meta until the PR for that filepath fix is merged.

**Comment by TylerAPfledderer** [comment]
@nikolovlazar this is fine now to review. I manually updated the search-meta regen so it is up-to-date. 👍🏼 ⚡

**Comment by nikolovlazar** [comment]
Awesome! Looks like it's ready to be merged. Just take care of the conflicts first and let me know.

**Comment by nikolovlazar** [comment]
I'm sorry, @TylerAPfledderer. Your other PR produced new conflicts 😅

**Comment by TylerAPfledderer** [comment]
Try again @nikolovlazar!

**Pull request merged**
