### PR TITLE
feat: add 'Edit this page on GitHub' link

### PR DESCRIPTION
**Pull request by samuliasmala**
## 📝 Description

Add a link to the end of each page (except changelog) to edit the page on GitHub.

## ⛳️ Current behavior (updates)

No link from document page to directly edit it

## 🚀 New behavior

Link added to the end of each page to provide easy way to access and edit the documentation

## 💣 Is this a breaking change (Yes/No):

No

### CODE REVIEW

**Comment by nikolovlazar** [comment]
This is great, @samuliasmala! Thanks for opening this PR 💖 A few things that I've noticed:
- Since I have write access to the repo, I'm taken directly into the Edit Mode, which is fine I guess
- If I'm not logged in, I'm taken to the GitHub Login page and I'd need to log in first to see what the page is
- If I'm logged in, but I don't have write access to the repo but a fork on my account, I'll still see the editor, but I'll be met with an alert
   `You're making changes in a project you don't have write access to. Submitting a change will write it to a new branch in your fork, so you can send a pull request`.
- A different scenario happens if I'm logged in, don't have write access, but also don't have a fork on my account.

To provide a consistent experience, I think leading the user to just the page without the Edit Mode will be better. The users will then chose if they want to fork it, open Visual Studio Code on that page, or use the GitHub editor right there on the spot.

**Comment by samuliasmala** [comment]
Thanks for the comments! You're correct, the link behavior will indeed vary from user to user so it's better to open the file in reading mode. I've updated the PR accordingly.

**Comment by nikolovlazar** [comment]
Looking good! Thanks @samuliasmala 💖

**Comment by nikolovlazar** [comment]
@allcontributors please add @samuliasmala for code

**Pull request merged**
