### PR TITLE
docs(faq): add faq page to docs

### LINKED ISSUE #12: Create a FAQ page
### Description

Create a FAQ page where we can answer the most commonly asked questions on Discord, Twitter or GitHub.

### Problem Statement/Justification

There are new developers getting started with Chakra UI every day. Most of them ask the same questions on Discord/Twitter/GitHub, and wait for someone to answer them. Having a FAQ page will help the newcomers progress easier and faster.

### Proposed Solution or API

Similarly to how the Resources page works, we can create `pages/faq.tsx` which will read the Q&As from `configs/faq.json`.

See `pages/resources.tsx` to see how it's implemented.

### PR DESCRIPTION
**Pull request by noobinthisgame**
Closes #12 

## 📝 Description

Adds a FAQ page to the documentation.

## 🚀 New behavior

A FAQ page is available in the docs

## 💣 Is this a breaking change (Yes/No):

No

## 📝 Additional Information
I have built this to work as described in the issue. I was wondering on the way if it would make more sense to use mdx for the FAQ, which would enable example and more complex structures of questions / answers (e.g. code examples)

### CODE REVIEW

**Review by lazarnikolov94 — CHANGES_REQUESTED** [review]
This works! But before it's ready to be merged, please add it to the omnisearch as well. Also, it's not visible on mobile.

**Comment by noobinthisgame** [comment]
Right, forgot about omnisearch thanks! I'll have a look what happened to Mobile :)

**Comment by noobinthisgame** [comment]
@lazarnikolov94 Is there a specific way to generate new search-meta content for omnisearch ?

**Comment by lazarnikolov94** [comment]
> @lazarnikolov94 Is there a specific way to generate new search-meta content for omnisearch ? Or can i just go ahead an add something manually. Didn't find much in the code.

There's a script, but it's currently missing in the new repo. #15 addresses that issue.

**Comment by noobinthisgame** [comment]
Closed this after i messed up with git and decided to switch to mdx for the base of the faq page. See #50

**Pull request closed without merging**
