### PR TITLE
Made correction in Flexbox section

### PR DESCRIPTION
**Pull request by eedrxs**
`rowGap` and `columnGap` properties were in kebab-case. Changed them to pascalCase.

### CODE REVIEW

**Comment by nikolovlazar** [comment]
@eedrxs can you update your main branch? The build is failing because of a package dependency issue that I fixed probably after you opened the PR, but the fix is already in the `main` branch. Sync it up and do another push, the build should fix itself.

**Comment by eedrxs** [comment]
@nikolovlazar okay then. I'd do just that.

**Comment by eedrxs** [comment]
@nikolovlazar I've made the updates and all checks were passed. The PR can be merged now.

**Comment by nikolovlazar** [comment]
Awesome! Thanks @eedrxs! 🙌

**Pull request merged**
