### PR TITLE
docs: add component style types in examples

### PR DESCRIPTION
**Pull request by m4x3d**
Closes -> no Issue atm

## 📝 Description

Adds informations of the current typing for Component Styles as well as informations about available parts in multipart components.

## ⛳️ Current behavior (updates)

At the moment there are no informations about these two topics.

## 🚀 New behavior

Improved Docs with more background informations about theming and 'low level' type support for the component styles.

## 💣 Is this a breaking change (Yes/No):

No

## 📝 Additional Information

Good for beginners I guess, helped me a lot with my first steps last year. :)

### CODE REVIEW

**Review by nikolovlazar — CHANGES_REQUESTED** [review]
Thank you for opening this PR, @m4x3d. Let's also add `import type { ComponentStyleConfig } from '@chakra-ui/theme'` on top of the code blocks to make it even more clearer.

**Comment by m4x3d** [comment]
Thanks for the quick response @nikolovlazar. 

Just added the imports and remove redundant parts in the comments.

**Review by nikolovlazar — APPROVED** [review]

**Comment by nikolovlazar** [comment]
Beautiful! Thanks again, @m4x3d.

**Comment by nikolovlazar** [comment]
@allcontributors please add @m4x3d for docs.

**Comment by aaarichter** [comment]
hey @nikolovlazar 

I just saw your suggestion for a typed example. But all code examples in the docs are for `jsx`

**Comment by nikolovlazar** [comment]
> hey @nikolovlazar
> 
> I just saw your suggestion for a typed example. But all code examples in the docs are for `jsx`

What do you mean, @aaarichter? The typed example in this PR is for creating a custom component style.

**Comment by m4x3d** [comment]
Thanks @aaarichter, did not see that tbh.

He meant that the language identifier of the code block is jsx but with types it is tsx.

I can fix that later if you want @nikolovlazar. :)

**Comment by nikolovlazar** [comment]
Ah, got it! Nice catch @aaarichter!

**Comment by aaarichter** [comment]
maybe that could be some future improvement to the docs to have a switch between jsx and tsx code examples

**Pull request merged**
