### PR TITLE
refactor: add algolia search

### LINKED ISSUE #973: Props missing for Box component in documentation
### Description

when I clicked the props option on Box Component documentation, I expected the list of props to load but I did not load anything.

### PR DESCRIPTION
**Pull request by noobinthisgame**
Closes #973 

## 📝 Description

This PR adds the algolia search with a custom way to list results to improve the search experience of our users. Also removing the custom solution improves the maintanability of the docs.

## ⛳️ Current behavior (updates)

> Please describe the current behavior that you are modifying

## 🚀 New behavior

> Please describe the behavior or changes this PR adds

### CODE REVIEW

**Comment by segunadebayo** [comment]
cc: @noobinthisgame

Thanks for working on this. Instead of throwing the custom solution away, let's move to the recipes section in the docs. We'll call it "OmniSearch". Over time, we might consider moving it into Chakra as well.

Thanks

**Comment by noobinthisgame** [comment]
@segunadebayo my pleasure !

I was planning on keeeping it anyway in case we are moving back because feedback on the new search is bad :)

**Comment by noobinthisgame** [comment]
@segunadebayo @nikolovlazar In case you wanna review this, I had to add to adjust some Headings in the docs files for better indexing. The important files to check here are the algolia-search.tsx related ones.

**Comment by noobinthisgame** [comment]
This attempt to add algolia search did not work out. Closing this for now.

**Pull request closed without merging**
