### PR TITLE
docs: advanced formik integration

### LINKED ISSUE #407: (docs): add recipe for advanced Formik integration with Chakra UI
### Subject

Recipe 

### Description

As discussed in https://github.com/chakra-ui/chakra-ui-docs/issues/374 a nice improvement would be a detailed recipe on how to integrate Formik with custom components and more advanced forms.

For that a new recipe page in the components section would be really nice.

### PR DESCRIPTION
**Pull request by aacevski**
Closes #407 

## 📝 Description
I've created a recipe for advanced Formik integration.

## 🚀 New behavior
Now the users can see a more advanced example of how they can use ChakraUI with Formik, especially with Chakra components such as the radio button as an image. On top of that, I've created a SandPack since there were multiple files and I think that would be much better.

## 💣 Is this a breaking change (Yes/No):
No.

### CODE REVIEW

**Comment by aacevski** [comment]
@nikolovlazar, should I add this page on the resources sidebar as well?

**Comment by nikolovlazar** [comment]
@aacevski we definitely should. I think it's better if we do the following changes:
- Create a new group "Recipes"
- Put the "Advanced Formik Integration" in the new Recipes group
- Move the "Atlaskit editable" into the new Recipes group
- Put the Recipes group between the "Advanced" and "Integrations" groups

Here's an idea of how it should look like:
CleanShot 2022-03-19 at 07 50 47@2x

**Comment by aacevski** [comment]
I've done just that, thanks for the input!

**Review by noobinthisgame — APPROVED** [review]
Great work @aacevski !!

**Comment by aacevski** [comment]
@nikolovlazar this is ready to be reviewed again, I've changed the wording! 🚀

**Review by nikolovlazar — APPROVED** [review]
LGTM!

**Pull request merged**
