### PR TITLE
refactor: use next image component instead of avatar

### LINKED ISSUE #196: Update images on the homepage to use `next/image`
### Subject

Image Optimization

### Description

Update images on the homepage to use `next/image` to improve the page load performance and lighthouse

### PR DESCRIPTION
**Pull request by wattanx**
Closes #196

## 📝 Description
Update images on the homepage to use `next/image` to improve the page load performance and lighthouse

## ⛳️ Current behavior (updates)
スクリーンショット 2022-02-12 15 42 44

スクリーンショット 2022-02-12 15 19 33

## 🚀 New behavior
スクリーンショット 2022-02-12 15 56 28

## 💣 Is this a breaking change (Yes/No):
No

### CODE REVIEW

**Comment by nikolovlazar** [comment]
Hi @wattanx. Is this still a draft PR?

**Comment by wattanx** [comment]
Sorry, I didn't know if this would work so I had to draft it.
It seems to work a little, so I'll remove the draft.

**Comment by nikolovlazar** [comment]
Looks good! Would you mind fixing another issue on the way? It seems that the Individual Sponsors images are square, but as I remember they were circle. Something must've happened along the way. Can you round them in this PR?
CleanShot 2022-02-16 at 08 17 45@2x

**Comment by wattanx** [comment]
@nikolovlazar 
I have also modified the Individual Sponsors images.

**Pull request merged**
