### PR TITLE
docs(theming): added list theming docs

### LINKED ISSUE #1077: Theming: List
### Subject

List

### Description

Create a basic theming documentation for the `List` component that showcases how you can style it.

Theming file: [List theming file](https://github.com/chakra-ui/chakra-ui-docs/blob/main/content/docs/components/list/theming.mdx)

### Template Reference

For single part components, feel free to use the `Button` component theming doc as a template reference: [Button theming](https://github.com/chakra-ui/chakra-ui-docs/blob/main/content/docs/components/button/theming.mdx).

For multipart components, feel free to use the `Input` component theming doc as a template reference: [Input theming](https://github.com/chakra-ui/chakra-ui-docs/blob/main/content/docs/components/input/theming.mdx).

### PR DESCRIPTION
**Pull request by GKosheev**
Closes #1077

## 📝 Description

> Adding `List` theming docs

## 📝 Additional Information

>SVG image of `List` anatomy needs to be inserted

### CODE REVIEW

**Review by aacevski — CHANGES_REQUESTED** [review]
image
image
image

Hey @GKosheev, I found some issues. The formatting is wrong in the `App.tsx` and in the `ListTheme.tsx`. On top of that the color mode switch is fixed and isn't moving when I scroll.

**Review by aacevski — CHANGES_REQUESTED** [review]
Hey @GKosheev, I have some requests:
- Can we make the lists fit the height on the screen so it's not scrollable - or make the scroll minimal? A suggestion would be to make them smaller.
- For the custom variant, I have some suggestion that I found on the web so it's a little more creative:
image

**Comment by GKosheev** [comment]
@aacevski, I tried to follow the design from the screenshot and I came up with the following solution for the custom variant: 

```jsx
<Flex align={"center"}>
  <ListIcon as={MdOutlineSell} />
  <ListItem>Consectetur adipiscing</ListItem>
</Flex>
```

```javascript
item: {
  bg: mode("orange.100", "orange.400")(props),
  borderRadius: "30px",
  w: "full",
  p: 2,
},
icon: {
  color: mode("orange.200", "orange.400")(props),
},
```
 
Light mode:

custom theme light mode

Dark mode:

custom theme dark mode



Apart from that, I made items shorter and smaller so they fit in `650x500`:

Lists with


While I'm figuring out the reason why there is a significant gap between `ordered` and `unordered` lists, is there anything else you'd like me to improve/change in the current version?

**Comment by aacevski** [comment]
https://gist.github.com/aacevski/c0ec82a50825442c2c395588c1f34885
This is the anatomy, you can add it. Meanwhile I'll look into the Showcase examples.

**Comment by GKosheev** [comment]
It turns out that the `container` with markers (`ol` or `ul`) has a predefined `margin-left`, which enables spacing between those first 2 lists. I couldn't identify where this value comes from, but I set `margin` to `0` with the `!important` rule.

**Comment by GKosheev** [comment]
@aacevski, would it be ok if I make a PR for the issues I created last week, or should I wait for the review first? It's related to the `SkeletonText` component. I debugged and found all the areas that cause unexpected animation and styling behavior. I also proposed solutions for both of the problems within the issues.

Issues numbers are `7230` and `7237` (within the `chakra-ui` repository).

**Review by aacevski — CHANGES_REQUESTED** [review]
Hey, I still wasn't happy with the showcase area, so I made some changes, you can look at them here and apply them:
https://codesandbox.io/s/pensive-waterfall-vterwj?file=/src/theme.ts

**Review by aacevski — APPROVED** [review]

**Pull request merged**
