### PR TITLE
add rootProps to menulist documentation

### PR DESCRIPTION
**Pull request by AyoubSayah**
Closes # 

## 📝 Description

> Add a brief description

## ⛳️ Current behavior (updates)

there is not rootProps documentation in the doc
## 🚀 New behavior
add rootpPops documentation

> Please describe the behavior or changes this PR adds

## 💣 Is this a breaking change (Yes/No):
no

### CODE REVIEW

**Review by nikolovlazar — CHANGES_REQUESTED** [review]
Hello @AyoubSayah! Thank you for opening this PR. The way we display the props here is by generating the `props-docs` package from the main repo. In order to show them, I suggest you do the following:
- Clone the [main repo](https://github.com/chakra-ui/chakra-ui)
- Open `packages/menu/src/menu.tsx`
- Find the `MenuListProps` interface on line 123
- Add a multi-line comment above the `rootProps` like this:
```javascript
/**
  * Props that get forwarded down to Popper.js.
  */
```
- Run `yarn build` and `yarn build:prop-docs` to be sure that the project builds
- Open a PR in the main repo

When that PR gets merged, and a new release happens, you'll need to update the docsite. Instead of adding the line you've added, add this: `<PropsTable of='MenuList' />`. This will render the Props Table with the description you've added in the main repo.

I know this process might seem tedious, but it counts as two contributions 😊 If you need any help along the process, don't hesitate to reach out.

Thank you!

**Comment by AyoubSayah** [comment]
hi @nikolovlazar  , this is my first contribution thank you for your help

**Comment by nikolovlazar** [comment]
No worries, @AyoubSayah! I'm here to make it easier for you to do your first contribution.

**Comment by nikolovlazar** [comment]
Hi @AyoubSayah! Did you open a PR in the main repo for this? Don't forget to link it with this PR, so we can track it better.

**Comment by AyoubSayah** [comment]
hi @nikolovlazar  , I think i didn't I thought that this is one is a separate project , i made 2 pr in docs and main repo

**Comment by nikolovlazar** [comment]
@AyoubSayah I don't see your PR in the main repo. Are you sure you opened it?

**Comment by AyoubSayah** [comment]
@nikolovlazar  yes its aleardy merged  i guess 
image

**Comment by nikolovlazar** [comment]
@AyoubSayah we recently pushed a release. Can you merge `main` back into your PR before we merge it?

**Comment by AyoubSayah** [comment]
@AyoubSayah done i guess

**Pull request merged**
