### PR TITLE
docs: add docs for the new htmlSize prop

### PR DESCRIPTION
**Pull request by noobinthisgame**
Docs for the following PR: https://github.com/chakra-ui/chakra-ui/pull/5507

## 📝 Description

Add docs for the new htmlSize prop with an example on how to use it.

## ⛳️ Current behavior (updates)

There is no htmlSize prop, thus no docs.

## 🚀 New behavior

There is docs for the new prop.

## 💣 Is this a breaking change (Yes/No):

No

## 📝 Additional Information

Should only be merged when the PR gets released, to not confuse users.

### CODE REVIEW

**Comment by noobinthisgame** [comment]
@nikolovlazar would it make sense to have a label for PRs like this one that only should be merged when the feature is released in the main repo ?

**Comment by nikolovlazar** [comment]
> @nikolovlazar would it make sense to have a label for PRs like this one that only should be merged when the feature is released in the main repo ? 

Yeah definitely! I'll create one right away.

**Comment by nikolovlazar** [comment]
I think also converting it to draft is a good idea, just to be sure that it's not going to be merged.

**Comment by noobinthisgame** [comment]
Yeah thats a great Idea aswell!

**Review by TimKolberger — APPROVED** [review]
lgtm 🚀

**Pull request merged**
