### PR TITLE
docs(Other): add show-hide page.

### PR DESCRIPTION
**Pull request by TylerAPfledderer**
## 📝 Description

Add documentation for the Media Query `Show` and `Hide` components

## ⛳️ Current behavior (updates)

N/A

## 🚀 New behavior

N/A

## 💣 Is this a breaking change (Yes/No):

No

### CODE REVIEW

**Comment by nikolovlazar** [comment]
Thanks for opening this PR, @TylerAPfledderer! I've got a few notes:

- You need to add the "Show / Hide" page to the search meta as well: `yarn search-meta:gen`. This will add a link to this page in the omni search.
- You also need to add a props table at the bottom of your mdx file:
```typescript
## Props

<PropsTable of='Show' />
```

As for the Props table, I've created an issue on the `chakra-ui` repo: https://github.com/chakra-ui/chakra-ui/issues/5573. What you could do is add the `PropsTable` at the bottom, and wait until the issue is resolved and a new version of Chakra UI is published.

**Comment by nikolovlazar** [comment]
**Update**: I've opened a PR in the `chakra-ui` repo that adds the descriptions. Here's how the props table would look like once the new Chakra UI version comes out:

CleanShot 2022-02-14 at 08 26 16@2x

**Comment by TylerAPfledderer** [comment]
Hey @nikolovlazar!

Would you know when to expect that patch release to come out?

**Comment by nikolovlazar** [comment]
Not sure, @TylerAPfledderer. Two weeks, three, at most.

**Comment by TylerAPfledderer** [comment]
Sounds good, thank you.

**Comment by nikolovlazar** [comment]
@TylerAPfledderer can you add this at the bottom of the MDX file:
```markdown
## Props

<PropsTable of='Show' />
```

**Comment by TylerAPfledderer** [comment]
@nikolovlazar pushed the `PropsTable` and updated `search-meta.json`.

**Comment by noobinthisgame** [comment]
@nikolovlazar This can now be merged :)

**Comment by nikolovlazar** [comment]
@TylerAPfledderer almost ready to be merged! What's left to do is to bump the `@chakra-ui/prop-docs` package to `1.0.49`. When you open the new page you should see this at the bottom:
image

**Comment by TylerAPfledderer** [comment]
@nikolovlazar checked in the local with the updated package. Works as expected!

**Comment by nikolovlazar** [comment]
@TylerAPfledderer you forgot to push the `package.json` and `yarn.lock` files. That's why your vercel deployment doesn't show the descriptions.

**Comment by TylerAPfledderer** [comment]
@nikolovlazar I saw my error. I've pushed the updated `package.json` and `yarn.lock`.

**Pull request merged**
