### PR TITLE
chore: restructure docs and support theming docs

### PR DESCRIPTION
**Pull request by segunadebayo**
## 📝 Description

This PR aims to restructure the docs and provide a way to document the theming guide for each component. After reviewing the current structure, I think it has gotten more complex over time.

- Move component docs to separate folders that contain `usage`, `props`, `theming`
- Remove unneeded nesting in the content of the doc in favor of adding a `category` frontmatter field
- Move MDX content out of pages into a dedicated `content` folder
- Simplify our component paths `docs/components/form/button` => `docs/components/button`. This makes the path guessable without having to know the "category" it belongs to.

## 💣 Is this a breaking change (Yes/No):

Partially. We'll need to update the Next.js redirect function to account for URL changes.

## 📝 Additional Information

We now need to write the docs for all the different components over time, after this PR is merged

### CODE REVIEW

**Comment by noobinthisgame** [comment]
I love those changes! Makes it much easier to use and easier to find stuff!

**Comment by noobinthisgame** [comment]
I did a quick review from the current work @segunadebayo. Just wanted too let you know that the overview page for styled-system is behaving strangely. Also what do you think about making the different boxes showcasing the components a bit smaller to fit more on one page to make it easier to navigate all of them ?

**Comment by segunadebayo** [comment]
@noobinthisgame Thanks for the review, I'm aware of the issues and trying to resolve all of them.

Good idea regarding the component overview boxes. I'll try that.

**Comment by nikolovlazar** [comment]
I like the restructure! All of the recipes are in one place, but I've noticed we've got 2 recipes under the Styled System category (https://chakra-ui.com/docs/styled-system/recipes/page-specific-color-mode and https://chakra-ui.com/docs/styled-system/recipes/using-fonts) that aren't included in the new structure.

**Review by nikolovlazar — APPROVED** [review]
LGTM! 👌

**Pull request merged**
