### PR TITLE
docs: Update framer-motion instruction to @^6

### PR DESCRIPTION
**Pull request by curdin**
Closes # nil

## 📝 Description

Since https://github.com/chakra-ui/chakra-ui/commit/f1d02474983dc8277e767dc729abc3cbb02cfe10 framer-motion@^6 is a valid dependency.
This change updates all instructions to use this latest version

## ⛳️ Current behavior (updates)

Current references instruct the user to install framer-motion@^5

## 🚀 New behavior

> User is instructed to install framer-motion@^6

## 💣 Is this a breaking change (Yes/No):

No

### CODE REVIEW

**Comment by nikolovlazar** [comment]
@TimKolberger are we confident that everything works well with Framer Motion v6?

**Comment by TimKolberger** [comment]
Yes, framer motion just moved the three JS integration to another package in v6: [Framer Motion alchangelog](https://github.com/framer/motion/blob/main/CHANGELOG.md#600-2022-01-19) 👍

**Review by nikolovlazar — CHANGES_REQUESTED** [review]
There's another install command in `/docs/getting-started` that still points to v5.

**Comment by curdin** [comment]
@nikolovlazar it helps when I commit all files :) 
`/docs/getting-started` update added

**Pull request merged**
