### PR TITLE
docs: Add Filters Section to Style-Props Page

### LINKED ISSUE #258: docs(filters): Add a Filters section in Style Props
Referencing #210. Add a section for the Filters props in the Style Props page.

### PR DESCRIPTION
**Pull request by sohamsshah**
Closes #258 

## 📝 Description

This PR adds Filter Section to the Docs by taking reference from the prop definition defined in [`packages/styled-system/src/config/filter.ts](https://github.com/chakra-ui/chakra-ui/blob/main/packages/styled-system/src/config/filter.ts)

Have added examples for:
- Filter (with and without filter="auto")
- Backdrop Filter (with and without backdrop-filter="auto")

## ⛳️ Current behavior (updates)

Currently, the section doesn't exist in Styled-Prop definition.

## 🚀 New behavior

This PR adds the below documentation:
image
image
image

## 💣 Is this a breaking change (Yes/No):

No

## 📝 Additional Information
Will be active to hear if any changes or suggestions are required in the provided examples or the Prop Definitions. Thank you!

### CODE REVIEW

**Comment by nikolovlazar** [comment]
Looking good! Before we proceed, could you make the code examples live? Meaning, provide some examples so people can see the effect of those props.

**Review by nikolovlazar — CHANGES_REQUESTED** [review]
Looking good! Before we proceed, could you make the code examples live? Meaning, provide some examples so people can see the effect of those props.

**Comment by sohamsshah** [comment]
Sure, I will do the changes and get back to you shortly

**Comment by nikolovlazar** [comment]
@sohamsshah I'm going to merge this PR and open a new issue that makes the examples live and editable.

**Comment by rayraspberry** [comment]
this doesn't seem to work in the theme and style files, only applied to individual components.
Can anyone confirm backdropFilter and backdropBlur functionality works on a global or component style level rather than just on individual tags?
image
Thx

**Pull request merged**
